# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'agregar_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Agregar(object):
    def setupUi(self, Agregar):
        Agregar.setObjectName("Agregar")
        Agregar.setEnabled(True)
        Agregar.setMinimumSize(QtCore.QSize(414, 262))
        Agregar.setMaximumSize(QtCore.QSize(414, 262))
        self.centralwidget = QtWidgets.QWidget(Agregar)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 20, 391, 211))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.txtNombreParticula = QtWidgets.QLineEdit(self.widget)
        self.txtNombreParticula.setObjectName("txtNombreParticula")
        self.horizontalLayout_9.addWidget(self.txtNombreParticula)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.txtCantidadProtones = QtWidgets.QLineEdit(self.widget)
        self.txtCantidadProtones.setObjectName("txtCantidadProtones")
        self.horizontalLayout_10.addWidget(self.txtCantidadProtones)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_11 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_13.addWidget(self.label_11)
        self.txtCantidadNeutrones = QtWidgets.QLineEdit(self.widget)
        self.txtCantidadNeutrones.setObjectName("txtCantidadNeutrones")
        self.horizontalLayout_13.addWidget(self.txtCantidadNeutrones)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_12 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_14.addWidget(self.label_12)
        self.txtCantidadElectrones = QtWidgets.QLineEdit(self.widget)
        self.txtCantidadElectrones.setObjectName("txtCantidadElectrones")
        self.horizontalLayout_14.addWidget(self.txtCantidadElectrones)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.btnAgregarP = QtWidgets.QPushButton(self.widget)
        self.btnAgregarP.setObjectName("btnAgregarP")
        self.verticalLayout.addWidget(self.btnAgregarP)
        Agregar.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Agregar)
        self.statusbar.setObjectName("statusbar")
        Agregar.setStatusBar(self.statusbar)

        self.retranslateUi(Agregar)
        QtCore.QMetaObject.connectSlotsByName(Agregar)

    def retranslateUi(self, Agregar):
        _translate = QtCore.QCoreApplication.translate
        Agregar.setWindowTitle(_translate("Agregar", "Agregar Particula"))
        self.label_7.setText(_translate("Agregar", "Nombre de particula:"))
        self.label_8.setText(_translate("Agregar", "Cantidad de protones:"))
        self.label_11.setText(_translate("Agregar", "Cantidad de neutrones:"))
        self.label_12.setText(_translate("Agregar", "Cantidad de electrones:"))
        self.btnAgregarP.setText(_translate("Agregar", "Agregar"))
